### ISSUE TITLE
Documentation 

### ISSUE THREAD

**Issue by WolfgangFahl** [PascalNoisette/mediawiki-extensions-Slides#1]
@PascalNoisette  it's great that you are creating a modern SlideShow extension.
What syntax does it follow? Is it compatible with S5SlideShow?
How does it work? https://revealjs.com/ is huge and i don't see how this relates to MediaWiki pages .. https://revealjs.com/markup/ shows html markup not mediawiki markup - how is the one translated into the other? 
https://www.mediawiki.org/wiki/Extension:S5SlideShow was the orginal
Do you have a demo wiki somewhere?
http://media.bitplan.com/index.php/S5SlideShow has links to some demo slides which don't work any more with MediaWiki 1.35 LTS - would this be a replacement that offers action=slide again?
What do you need to get things published in the wikimedia extension catalog?
What is necessary to try out this extension?
What should be the name of this extension?

**Comment by PascalNoisette** [comment]
My idea was using a maximum of wikisyntax instead of custom proprietary headingmark, so the wiki headings are retrieved and transformed into reveal slides.
As you noticed, there is not even styles or further configurations like in S5SlideShow, this module is at is earliest stages, with no doc and no demo.
That said, this module would be a replacement for a action=slide yes.
Regards, Pascal
